json.id album.id
json.artistName album.artist.username
json.artistId album.artist.id
json.title album.title
json.description album.description
json.year album.year
json.genre album.genre
json.image_url asset_path(album.image.url)
json.tracks album.tracks
